clc;

figure (1)
subplot(2,1,1)
plot(x.wr.time, x.wr.signals.values)
grid on;
title('Motor Speed')
xlabel('Time [sec]')
ylabel('Speed [rad/sec]')
axis([0 10 0 340])
subplot(2,1,2)
plot(x.tau_e.time, x.tau_e.signals.values)
grid on;
title('Electrical Torque')
xlabel('Time [sec]')
ylabel('Torque [Nm]')

figure (2)
subplot(2,1,1)
plot(x.i_ampl.time, x.i_ampl.signals.values)
grid on;
title('Current Amplitude')
xlabel('Time [sec]')
ylabel('Current [A]')
subplot(2,1,2)
plot(x.psi_ampl.time, x.psi_ampl.signals.values)
grid on;
title('Rotor Flux Amplitude')
xlabel('Time [sec]')
ylabel('Flux [Wb]')
axis([0 10 0 0.8])

figure(10)
subplot(2,2,1)
plot(x.wr.time, x.wr.signals.values)
grid on;
title('Motor Speed')
xlabel('Time [sec]')
ylabel('Speed [rad/sec]')
axis([0 1.3 0 340])
subplot(2,2,2)
plot(x.tau_e.time, x.tau_e.signals.values)
grid on;
title('Electrical Torque')
xlabel('Time [sec]')
ylabel('Torque [Nm]')
axis([0 1.3 -20 50])
subplot(2,2,3)
plot(x.i_ampl.time, x.i_ampl.signals.values)
grid on;
title('Current Amplitude')
xlabel('Time [sec]')
ylabel('Current [A]')
axis([0 1.3 0 45])
subplot(2,2,4)
plot(x.psi_ampl.time, x.psi_ampl.signals.values)
grid on;
title('Rotor Flux Amplitude')
xlabel('Time [sec]')
ylabel('Flux [Wb]')
axis([0 1.3 0 0.8])

figure (20)
plot(x.wr.signals.values, x.tau_e.signals.values)
grid on;
xlabel('Speed [rad/sec]')
ylabel('Electrical Torque [Nm]')

figure (3)
subplot(2,1,1)
plot(x.wr.time, x.wr.signals.values, y.wr.time, y.wr.signals.values, z.wr.time, z.wr.signals.values)
grid on;
title('Motor Speed')
legend('No Load', 'bw_m Load', 'bw_m^2 Load')
legend('location','best')
xlabel('Time [sec]')
ylabel('Speed [rad/sec]')
axis([0 5 0 340])
subplot(2,1,2)
plot(x.tau_e.time, x.tau_e.signals.values, y.tau_e.time, y.tau_e.signals.values, z.tau_e.time, z.tau_e.signals.values)
grid on;
title('Electrical Torque')
legend('No Load', 'bw_m Load', 'bw_m^2 Load')
ylabel('Torque [Nm]')
axis([0 5 -20 50])

figure (4)
subplot(2,1,1)
plot(x.i_ampl.time, x.i_ampl.signals.values, y.i_ampl.time, y.i_ampl.signals.values, z.i_ampl.time, z.i_ampl.signals.values)
grid on;
title('Current Amplitude')
legend('No Load', 'bw_m Load', 'bw_m^2 Load')
legend('location','best')
xlabel('Time [sec]')
ylabel('Current [A]')
axis([0 5 0 45])
subplot(2,1,2)
plot(x.psi_ampl.time, x.psi_ampl.signals.values, y.psi_ampl.time, y.psi_ampl.signals.values,'g', z.psi_ampl.time, z.psi_ampl.signals.values)
grid on;
title('Rotor Flux Amplitude')
legend('No Load', 'bw_m Load', 'bw_m^2 Load')
legend('location','best')
xlabel('Time [sec]')
ylabel('Flux [Wb]')
axis([0 5 0 0.8])

figure(30)
subplot(2,2,1)
plot(x.wr.time, x.wr.signals.values, y.wr.time, y.wr.signals.values, z.wr.time, z.wr.signals.values)
grid on;
title('Motor Speed')
xlabel('Time [sec]')
ylabel('Speed [rad/sec]')
axis([0 2.1 0 340])
subplot(2,2,2)
plot(x.tau_e.time, x.tau_e.signals.values, y.tau_e.time, y.tau_e.signals.values, z.tau_e.time, z.tau_e.signals.values)
grid on;
title('Electrical Torque')
xlabel('Time [sec]')
ylabel('Torque [Nm]')
axis([0 2.1 -20 50])
subplot(2,2,3)
plot(x.i_ampl.time, x.i_ampl.signals.values,y.i_ampl.time, y.i_ampl.signals.values,z.i_ampl.time, z.i_ampl.signals.values)
grid on;
title('Current Amplitude')
xlabel('Time [sec]')
ylabel('Current [A]')
axis([0 2.1 0 45])
subplot(2,2,4)
plot(x.psi_ampl.time, x.psi_ampl.signals.values, y.psi_ampl.time, y.psi_ampl.signals.values, z.psi_ampl.time, z.psi_ampl.signals.values)
grid on;
title('Rotor Flux Amplitude')
xlabel('Time [sec]')
ylabel('Flux [Wb]')
axis([0 2.1 0 0.8])

figure (5)
plot(x.wr.signals.values, x.tau_e.signals.values, x1.wr.signals.values, x1.tau_e.signals.values, x2.wr.signals.values, x2.tau_e.signals.values, x3.wr.signals.values, x3.tau_e.signals.values)
grid on;
legend('R_R^N', '2R_R^N', 'R_R^N /2', '4R_R^N')
legend('location','best')
xlabel('Speed [rad/sec]')
ylabel('Electrical Torque [Nm]')

figure (6)
subplot(2,1,1)
plot(x.wr.time, x.wr.signals.values, x1.wr.time, x1.wr.signals.values, x2.wr.time, x2.wr.signals.values, x3.wr.time, x3.wr.signals.values)
grid on;
title('Motor Speed')
legend('R_R^N', '2R_R^N', 'R_R^N /2', '4R_R^N')
legend('location','best')
xlabel('Time [sec]')
ylabel('Speed [rad/sec]')
axis([0 5 0 340])
subplot(2,1,2)
plot(x.tau_e.time, x.tau_e.signals.values, x1.tau_e.time, x1.tau_e.signals.values, x2.tau_e.time, x2.tau_e.signals.values, x3.tau_e.time, x3.tau_e.signals.values)
grid on;
title('Electrical Torque')
legend('R_R^N', '2R_R^N', 'R_R^N /2', '4R_R^N')
ylabel('Torque [Nm]')
axis([0 5 -20 60])

figure (7)
subplot(2,1,1)
plot(x.i_ampl.time, x.i_ampl.signals.values, x1.i_ampl.time, x1.i_ampl.signals.values, x2.i_ampl.time, x2.i_ampl.signals.values, x3.i_ampl.time, x3.i_ampl.signals.values)
grid on;
title('Current Amplitude')
legend('R_R^N', '2R_R^N', 'R_R^N /2', '4R_R^N')
legend('location','best')
xlabel('Time [sec]')
ylabel('Current [A]')
axis([0 5 0 45])
subplot(2,1,2)
plot(x.psi_ampl.time, x.psi_ampl.signals.values, x1.psi_ampl.time, x1.psi_ampl.signals.values, x2.psi_ampl.time, x2.psi_ampl.signals.values, x3.psi_ampl.time, x3.psi_ampl.signals.values)
grid on;
title('Rotor Flux Amplitude')
legend('R_R^N', '2R_R^N', 'R_R^N /2', '4R_R^N')
legend('location','best')
xlabel('Time [sec]')
ylabel('Flux [Wb]')
axis([0 5 0 0.8])

figure (8)
subplot(2,1,1)
plot(u.wr.time, u.wr.signals.values)
grid on;
title('Motor Speed')
xlabel('Time [sec]')
ylabel('Speed [rad/sec]')
axis([0 5 0 340])
subplot(2,1,2)
plot(u.tau_e.time, u.tau_e.signals.values)
grid on;
title('Electrical Torque')
xlabel('Time [sec]')
ylabel('Torque [Nm]')
axis([0 5 -80 60])

figure (9)
subplot(2,1,1)
plot(u.i_ampl.time, u.i_ampl.signals.values)
grid on;
title('Current Amplitude')
xlabel('Time [sec]')
ylabel('Current [A]')
axis([0 5 0 60])
subplot(2,1,2)
plot(u.psi_ampl.time, u.psi_ampl.signals.values)
grid on;
title('Rotor Flux Amplitude')
xlabel('Time [sec]')
ylabel('Flux [Wb]')
axis([0 5 0 0.8])

figure(11)
plot(u.v_alphabeta)
grid on;
title('Voltage Amplitude')
xlabel('Time [sec]')
ylabel('Voltage [V]')