%% SIMULATION 3: SIMPLE VECTOR CONTROL - INDUCTION MOTOR
% YLOPOIHSH DIANYSMATIKOY ELEGXOY MHXANHS EPAGWGHS
% ME DYNATOTHTA METRHSHS PROSANATOLISMOY TOY PEDIOY
clearvars;
clc;
%% PARAMETER SELECTION
% EPILOGH PARAMETRWN TASHS EISODOY
Vhat = 230*sqrt(2); f = 50; K = 1/sqrt(2); 
w = 2*pi*f;
phi_a = 0; phi_b = -2*pi/3; phi_c = -4*pi/3;
% EPILOGH PARAMETRWN MHXANHS
Rs = 2.2667; LM = 0.1237; Lsigma = 0.0227; RR = 0.8197; 
np = 2; J = 0.08; tL = 26.8; b1 = 0.1796; b2 = 0.0012;
% EPILOGH PARAMETRWN PLL
alphaP = 110; psi_hat = 0.62; 
kpp = 2*alphaP/psi_hat; kip = alphaP*alphaP/psi_hat;
% EPILOGH PARAMETRWN ELEGKTH REYMATOS
Iref = 9.2; Idref = psi_hat/LM; Iqref = sqrt(Iref^2-Idref^2); 
L = Lsigma; R = Rs + RR; alphaC = log(9)/1e-3;
Ra = alphaC*L - R; Kp = alphaC*L; Ki = alphaC*(R+Ra);
% EPILOGH PARAMETRWN DIAKOPTWN
sw1 = 0; sw2=0; sw3=0; refsw = 0;
%% SIMULATION FOR PLL
% PROSOMOIWSH EPILEGMENHS KATASTASHS KAI EPALHTHEYSH
% LEITOYRGIAS PLL
x = sim('sim3el17128');
%% SIMULATION FOR CURRENT CONTROL
% PROSOMOIWSH EPEITA APO YLOPOIHSH TOY DIANYSMATIKOY ELEGXOY
% KAI EPALHTHEYSH SWSTHS LEITOURGIAS TOY
sw1 = 1;
y = sim('sim3el17128');
refsw = 1; tL = 0;
y1 = sim('sim3el17128');
%% SIMULATION FOR CURRENT CONTROL WITH SATURATION & ANTIWINDUP
% PROSTHIKH SATURATION
% KAI EPALHTHEYSH SWSTHS LEITOURGIAS TOY
tL = 26.8; refsw = 0;
sw2 = 1;
z = sim('sim3el17128');
sw3 = 1;
u = sim('sim3el17128');